# Generated by Django 2.2 on 2020-03-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='idea',
        ),
    ]
